### ISSUE TITLE
Am I Misunderstanding the util Module and This Module's Dependency

### ISSUE THREAD

**Issue by alanjames1987** [isaacs/inherits#14]
The `util` module has an `inherits` function, which points to this `inherits` module.

https://github.com/defunctzombie/node-util/blob/master/util.js#L570

And this module `exports` an `inherits` method, which it gets from the `util` module.

https://github.com/isaacs/inherits/blob/master/inherits.js#L1

I'm guessing that this somehow makes sense but I am misunderstanding it.

Can you explain how they point to each other but still work?

**Comment by isaacs** [comment]
`util` is a built-in module in node, so doing `require('util')` will always return the built-in.

I'm not sure what @defunctzombie's `util` does, but yes, in general, it is fine to have modules refer to one another.  I'm assuming that http://npm.im/util is for browsers and other non-node environments, so probably it ought to load `require('inherits/inherits_browser.js')` or something?

**Comment by alanjames1987** [comment]
I understand. I thought the util library I linked to was the built in one, but it looks like a port of it's functionality to a module.

Thanks for the quick reply.
