### ISSUE TITLE
Phantom.js compatibility

### ISSUE THREAD

**Issue by LinusU** [isaacs/inherits#15]
[Phantom.js](http://phantomjs.org) dosen't ship with any builtin libraries :( and thus the shortpath for node.js dosen't work.

I'm trying to us [defunctzombie/commonjs-assert](https://github.com/defunctzombie/commonjs-assert) which depends on [defunctzombie/node-util](https://github.com/defunctzombie/node-util) which in turn depends on inherits.

When inherits does `require('util')` it will actually get back `defunctzombie/node-util`, which won't have any `inherits` defined since it's depending on this module for that.

**Comment by tellnes** [comment]
If you are in a browser you should get the `inherits_browser.js` file which does not have any dependencies. Maybe your are using a `require`-implementation which does not support the `browser` field in `package.json`?

**Comment by LinusU** [comment]
Hmm, yeah I guess that maybe the correct fix is for phantomjs to respect the `browser` field...

I can't load `inherits_browser.js` since all I do from my code is `require('assert')` which in turn does the described steps.

**Comment by impinball** [comment]
@LinusU I surrounded the original require with a try-catch. That *should* fix it.

**Comment by LinusU** [comment]
Actually I don't think it will. `require('util')` works, but returns an object that doesn't have an `inherits` property. Thus that modules will still export `undefined`.

Something like this could probably fix it:
```javascript
var util = require('util')

if (typeof util.inherits === 'function') {
  module.exports = util.inherits
} else {
  module.exports = require('./inherits_browser')
}
```

**Comment by impinball** [comment]
Should my latest update work better? It defaults to the browser module if requiring 'util' fails, or if util.inherits is not a function. Any other edge cases I can think of would literally require doing sanity checks on the function's behavior.

**Comment by LinusU** [comment]
Have you actually tried that code? It's throwing syntax error for me... And it also checks if `util` is a function (which it shouldn't be), not `util.inherits`. I'm not sure that the try catch is necessary, but if you want it I would write it like this:

```javascript
try {
  var util = require('util')

  if (typeof util.inherits !== 'function') {
    throw new TypeError('util.inherits is not a function')
  }

  module.exports = util.inherits
} catch (e) {
  module.exports = require('./inherits_browser')
}
```

**Comment by impinball** [comment]
Oops... Although the problem was that apparently, Phantom didn't export
"inherits". I'll go back and fix the code.

**Comment by impinball** [comment]
And my throw was just "throw, but the result doesn't matter".

**Comment by impinball** [comment]
This should work a little better. I totally wasn't paying attention to what code I was writing.
