### ISSUE TITLE
Would you be willing to publish a 1.0.1?

### ISSUE THREAD

**Issue by mmucklo** [isaacs/inherits#18]
Through a chain of dependencies, gulp 3.x is depending on inherits 1.

Unfortunately it doesn't have a license file (although I see that a license file was added at a later commit).

Would you be willing to publish a 1.0.1 to npmjs.org that has a license file included?

See: https://github.com/wearefractal/glob-watcher/issues/20

**Comment by isaacs** [comment]
Done.  Note that this is just a copy of v2, but with a version of 1.0.1.  That may cause problems, I don't know.

**Comment by mmucklo** [comment]
Thanks so much for the quick response - would it be possible to do a 1.0.1 that's based off of the 1.0.0 code base instead, just with a license file?

I have concern since upstream dependencies install inherits 1, that they will now be pulling in 1.0.1 not realizing that it's based off of inherits 2 and potentially breaking things.

**Comment by phated** [comment]
:+1: on `npm install`ing 1.0.0, adding a license file and publishing as 1.0.2

**Comment by isaacs** [comment]
@phated did that for 1.0.2

**Comment by phated** [comment]
thanks @isaacs

**Comment by mmucklo** [comment]
thanks!

**Comment by contra** [comment]
@isaacs thanks for being responsive and quick about correcting this :+1:
