### ISSUE TITLE
TypeError: inherits is not a function

### ISSUE THREAD

**Issue by geakstr** [isaacs/inherits#20]
I get it in Safari (9.1). All works in Chrome and Firefox.

`TypeError: inherits is not a function. (In 'inherits(Stream, EE)', 'inherits' is an instance of Object)`

![frontendy 2016-04-22 17-12-30](https://cloud.githubusercontent.com/assets/1496368/14742466/6f346d2e-08ad-11e6-9b3a-149dd034ae62.png)

`stream-browserify` `package.json` use `"inherits": "~2.0.1"`

**Comment by romanonthego** [comment]
@geakstr have you been able to resolve this issue? run into this one today.

**Comment by geakstr** [comment]
@romanonthego the problem was with dependencies (more concrete — `isomorphic-relay`).

**Comment by jimbofreedman** [comment]
@geakstr would you be able to elaborate? I'm struggling with this now.

**Comment by jimbofreedman** [comment]
@geakstr could you elaborate a bit more please? I've been hunting the same problem.

**Comment by geakstr** [comment]
@jimbofreedman We found that problem was with `isomorphic-relay` and were not going to do server rendering, therefore just deleted `isomorphic-relay` dep and all works fine. I'm sorry, I do not know more details about this problem.

**Comment by amirmohsen** [comment]
I've run into the same issue, but I'm not using isomorphic-relay. In my case, the problem is with [this line](https://github.com/sockjs/sockjs-client/blob/master/lib/event/emitter.js#L11) in sockjs-client.
